vim.keymap.set("n", "<leader>e", ":Neotree toggle<CR>", { desc = "Toggle Neo-tree" })
vim.keymap.set("n", "<leader>lv", "<cmd>Telescope live_grep<CR>", { desc = "Live Grep" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
vim.keymap.set("n", "<leader>an", "<cmd>NorminetteDisable<CR>", { desc = "Disable Norm" })
vim.keymap.set("n", "<leader>am", "<cmd>NorminetteEnable<CR>", { desc = "Enable Norm" })
vim.keymap.set("n", "<leader>ac", "<cmd>CopilotChat<CR>", { desc = "Talk to AI" })
vim.keymap.set("n", "<C-S-Left>", "<cmd>vertical resize -5<CR>")
vim.keymap.set("n", "<C-S-Right>", "<cmd>vertical resize +5<CR>")
vim.keymap.set("n", "L", "<cmd>BufferLineCycleNext<CR>", {})
vim.keymap.set("n", "H", "<cmd>BufferLineCyclePrev<CR>", {})
vim.keymap.set("n", "<leader>x", "<cmd>bdelete<CR>", { desc = "Close current buffer" })
vim.keymap.set("n", "<leader>fw", function()
	require("telescope.builtin").grep_string({ search = vim.fn.expand("<cword>") })
end, { desc = "Search word under cursor with Telescope" })
vim.keymap.set("n", "<leader>ls", "<cmd>LiveServerStart<CR>", { desc = "Start Hosting" })
vim.keymap.set("n", "<leader>lS", "<cmd>LiveServerStop<CR>", { desc = "Stop Hosting" })
